version: '3.8'

services:
  backend:
    build:
      context: ./prescripto_full-stack_doctor_appointment_app/backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/youraidoctor
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
